security:
    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser: 'bcrypt'

    providers:
        users_in_memory: { memory: null }
        developers:
            memory:
                users:
                    '%env(DEBUG_USERNAME)%': { password: '%env(DEBUG_ENCRYPTED_PASSWORD)%', roles: [ 'ROLE_DEBUG' ] }

    firewalls:
        dev:
            pattern: ^/(_(wdt)|css|images|js)/
            security: false
        profiler:
            pattern: ^/(_profiler)/
            provider: developers
            http_basic:
                realm: Secured Area
        main:
            anonymous: true
            lazy: true
            provider: users_in_memory

    access_control:
