security:
    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser: auto

    providers:
        developers:
            memory:
                users:
                    '%env(DEBUG_USERNAME)%':
                        password: '%env(DEBUG_ENCRYPTED_PASSWORD)%'
                        roles: [ 'ROLE_DEBUG' ]

    firewalls:
        profiler:
            pattern: ^/(_profiler)/
            provider: developers
            http_basic: ~
            stateless: true

    access_control:
        - { path: ^/(_profiler)/, roles: ROLE_DEBUG }
