volumes:
  rpps-db-data:

services:

  base:
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile.base
    image: rpps-api-base

  rpps-database:
    build:
      context: ./
      dockerfile: ./docker/apache/Dockerfile.${DOCKER_COMPOSE_ENV:-dev}
    container_name: rpps-data-item-container
    depends_on:
      - base
    command: ["make", "start-apache-prod"]
    restart: always
    ports:
      - "447:443"
    volumes_from:
      - app-data
    links:
      - rpps-db
    networks:
      - instamed
      - rpps_db

  app-data:
    image: alpine:3
    container_name: api-app-data-container
    volumes:
      - ./:/var/www/html/
      - type: bind
        source: ./test_db.sqlite
        target: /var/test_db.sqlite
    command: "true"

  rpps-db:
    image: mysql:8
    container_name: rpps-db-container
    restart: always
    ports:
      - "3334:3306"
    volumes:
      - rpps-db-data:/var/lib/mysql
      - ./docker/mysql/:/home/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    networks:
      - rpps_db

  icd_11_api:
    platform: linux/x86_64
    image: whoicd/icd-api:2.3.0
    environment:
     - include=2023-01_en
     - acceptLicense=true
     - saveAnalytics=false
    ports:
     - "89:80"
    networks:
     - instamed
     - rpps_db

networks:
  rpps_db:
    driver: bridge
  instamed:
    external: true
