version: '2.4'

volumes:
  db-data:

services:
  apache:
    build:
      context: ./
      dockerfile: ./docker/apache/Dockerfile.${DOCKER_COMPOSE_ENV:-dev}
    container_name: rpps-apache-container
    command: ["make", "start-apache-prod"]
    restart: always
    ports:
      - "446:443"
    volumes_from:
      - app-data
    links:
      - database

  app-data:
    image: alpine:3
    container_name: api-app-data-container
    volumes:
      - ./:/var/www/html/
      - type: bind
        source: ./test_db.sqlite
        target: /var/test_db.sqlite
    command: "true"

  database:
    image: mysql:8
    container_name: rpps-database-container
    restart: always
    ports:
      - "3333:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/:/home/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
