version: '2.4'

volumes:
  db-data:

services:
  apache:
    build:
      context: ./
      dockerfile: ./docker/apache/Dockerfile
    container_name: api-apache-container
    restart: always
    ports:
      - 8001:443
    volumes_from:
      - app-data
    links:
      - mysql

  app-data:
    image: alpine:3
    container_name: api-app-data-container
    volumes:
      - ./:/var/www/html/

    command: "true"

  mysql:
    image: mysql:5
    container_name: api-mysql-container
    restart: always
    ports:
      - 3333:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/:/home/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
