import-data: import-allergens import-ccam import-diseases import-drugs import-cities import-specialties import-rpps # Import all data except test data

import-allergens: # Import allergens' data
	docker-compose run --rm rpps-database php bin/console app:allergen:import

import-ccam: # Import CCAM data
	docker-compose run --rm rpps-database php bin/console app:ccam:import

import-diseases: # Import diseases' data
	docker-compose run --rm rpps-database php bin/console app:disease:import

import-drugs: # Import drugs' data
	docker-compose run --rm rpps-database php bin/console app:drugs:import

import-cities: # Import city, department, and region data
	docker-compose run --rm rpps-database php bin/console app:city:import --purge

import-specialties: # Import specialties' data
	docker-compose run --rm rpps-database php bin/console app:specialty:import

import-rpps: # Import RPPS data
	docker-compose run --rm rpps-database php bin/console app:rpps:import

import-test-data: # Import test data
	docker-compose run --rm rpps-database php bin/console app:test:create --legacy=true