## === Development === commands - meant to be used to run the project locally while developping on it

install-app: run composer-install setup-db ## Installs the application without importing the data

setup-dev: install-app load-fixtures ## Installs the application with the fixtures data

install: install-app import-data ## Installs the application & imports the data

composer-install: ## Runs composer install in the container to install backend dependencies
	docker-compose run --rm apache composer install

composer-require: ## Runs composer require in the container to add a new dependency
	docker-compose run --rm apache composer require $(package)

routes-dev: ## Lists all routes of the application
	make run-command command='debug:router'


shell: ## Gets a shell in the apache container
	docker-compose exec apache bash

clear-cache:
	make run-command command='cache:clear'

reactor:
	docker-compose run --rm apache vendor/bin/rector process src -v
