## === Development === commands - meant to be used to run the project locally while developping on it

install-app: run composer-install setup-db ## Installs the application without importing the data

setup-dev: install-app load-fixtures ## Installs the application with the fixtures data

install: install-app import-data ## Installs the application & imports the data

composer-install: ## Runs composer install in the container to install backend dependencies
	docker-compose run --rm rpps-database composer install

composer-require: ## Runs composer require in the container to add a new dependency
	docker-compose run --rm rpps-database composer require $(package)

routes-dev: ## Lists all routes of the application
	make run-command command='debug:router'


shell: ## Gets a shell in the rpps-database container
	docker-compose exec rpps-database bash

clear-cache:
	make run-command command='cache:clear'

# Loaded config default from "/var/www/html/.php-cs-fixer.dist.php"
csfixer:
	docker-compose exec rpps-database ./vendor/bin/php-cs-fixer fix -v src/

phpcbf:
	docker-compose exec rpps-database ./vendor/bin/phpcbf src/ --runtime-set ignore_warnings_on_exit true

phpcs:
	docker-compose exec rpps-database ./vendor/bin/phpcs --runtime-set ignore_warnings_on_exit true src

php-stan:
	docker-compose exec rpps-database ./vendor/bin/phpstan analyse -c phpstan.neon -l 6 src/

rector:
	docker-compose exec rpps-database ./vendor/bin/rector process src/ -v

lint:
	make phpcbf && make csfixer && make php-stan