import-data: import-allergens import-ccam import-diseases import-drugs import-rpps # Import all data but test data

import-allergens: # Import allergets' data
	docker-compose run --rm rpps-database php bin/console app:allergen:import

import-ccam: # Import CCAM' data
	docker-compose run --rm rpps-database php bin/console app:ccam:import

import-diseases: # Import diseases' data
	docker-compose run --rm rpps-database php bin/console app:disease:import

import-drugs: # Import drugs' data
	docker-compose run --rm rpps-database php bin/console app:drugs:import

import-rpps: # Import rpps' data
	docker-compose run --rm rpps-database php bin/console app:rpps:import

import-test-data: # Import test data
	docker-compose run --rm rpps-database php bin/console app:test:create --legacy=true
