name: create-test-db
description: Creates the test database
runs:
  using: 'composite'
  steps:
    - name: Create test database
      shell: bash
      env:
        DATABASE_URL: "/var/test_db.sqlite"
        DATABASE_ENGINE: "pdo_sqlite"
      run: |
        sudo chmod -R 777 ./var
        sudo touch ./var/test_db.sqlite
        sudo chmod 777 ./var/test_db.sqlite
        php bin/console doctrine:schema:update --force --env=test
        php bin/console doctrine:fixtures:load --env=test
        php bin/console cache:clear --env=test
