runs:
  using: 'composite'
  steps:
    - name: Create test database
      run: |
        sudo chmod -R 777 ./var
        sudo touch var/test_db.sqlite
        sudo chmod 777 var/test.sqlite
        php bin/console doctrine:schema:update --force --env=test
        php bin/console doctrine:fixtures:load --env=test
        php bin/console cache:clear --env=test
