name: Build docker image
description: Build the docker image passed as a parameter

inputs:
  registry_url:
    description: "The git registry your image is stored on"
    required: false
    default: ghcr.io
  registry_username:
    description: "The username of your registry user"
    required: true
  registry_password:
    description: "The password of your registry user"
    required: true
  docker_image:
    description: "The name of your image"
    required: true
  docker_file:
    description: "The extension of your Dockerfile"
    required: true
  github_token:
    description: "The Github PAT for composer"
    required: false
    default: ''
  docker_tag:
    description: "The tag you want to build"
    required: false
    default: latest
  base_image_tag:
    description: "The tag of the base image"
    required: false
    default: latest
  docker_env:
    description: "The environment image to build"
    required: false
    default: latest
  php_version:
    description: "The version of PHP to use"
    required: false
    default: '8.3'

runs:
  using: 'composite'
  steps:

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry_url }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker metadata
      id: docker-metadata
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.registry_url }}/${{ inputs.docker_image }}

    - name: Build test image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        builder: ${{ steps.buildx.outputs.name }}
        tags: ${{ inputs.registry_url }}/${{ inputs.docker_image }}:${{ inputs.docker_tag }}
        file: docker/apache/Dockerfile.${{ inputs.docker_file }}
        cache-from: type=registry,ref=${{ inputs.registry_url }}/${{ inputs.docker_image }}:${{ inputs.docker_tag }}-cached
        cache-to: type=registry,ref=${{ inputs.registry_url }}/${{ inputs.docker_image }}:${{ inputs.docker_tag }}-cached,mode=max
        build-args: |
          DOCKER_ENV=${{ inputs.docker_env }}
          BASE_IMAGE=${{ inputs.base_image_tag }}
          GITHUB_TOKEN=${{ inputs.github_token }}
          PHP_VERSION=${{ inputs.php_version }}
