name: Build docker image
description: Build the docker image passed as a parameter

inputs:
  registry_url:
    description: "The git registry your image is stored on"
    required: true
  registry_username:
    description: "The username of your registry user"
    required: true
  registry_password:
    description: "The password of your registry user"
    required: true
  docker_image:
    description: "The name of your image"
    required: true

runs:
  using: 'composite'
  steps:

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry_url }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker metadata
      id: docker-metadata
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.registry_url }}/${{ inputs.docker_image }}

    - name: Build test image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        builder: ${{ steps.buildx.outputs.name }}
        tags: ${{ inputs.registry_url }}/${{ inputs.docker_image }}:latest
        file: docker/apache/Dockerfile
        cache-from: type=registry,ref=${{ inputs.registry_url }}/${{ inputs.docker_image }}:cached
        cache-to: type=registry,ref=${{ inputs.registry_url }}/${{ inputs.docker_image }}:cached,mode=max
