App\Entity\Cim11ModifierValue:
  shortName: cim11_modifier_value
  attributes:
    allow_extra_attributes: false
    order:
      name: ASC
  collectionOperations:
    get: ~
  itemOperations:
    get: ~
