App\Entity\RPPS:
  shortName: Rpps
  order:
    name: ASC
  attributes:
    allow_extra_attributes: false
    pagination_partial: true
    pagination_client_partial: true
  collectionOperations:
    get: ~
  itemOperations:
    get: ~
