name: Deploy Staging

env:
  ENVIRONMENT: 'production'
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_TAG: 'latest'

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:

concurrency:
  group: production-release-${{ github.ref }}-1
  cancel-in-progress: true


jobs:
  docker-build-base:
    name: Build Base Image
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build staging image
        uses: ./.github/actions/build-docker-image
        with:
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          docker_image: ${{ env.IMAGE_NAME }}-base
          docker_file: "base"
          docker_tag: ${{ env.DOCKER_TAG }}

  docker-build-production:
    name: Build Latest Image
    runs-on: ubuntu-latest
    needs: docker-build-base
    if: startsWith(github.ref_name, 'main')
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build staging image
        uses: ./.github/actions/build-docker-image
        with:
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          docker_file: 'deployed'
          docker_env: ${{ env.ENVIRONMENT }}
          docker_tag: ${{ env.ENVIRONMENT }}
          base_image_tag: 'latest'
          github_token: ${{ secrets.GITHUB_TOKEN }}


  docker-build-tag:
    name: Build tag Image
    runs-on: ubuntu-latest
    needs: docker-build-base
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build staging image
        uses: ./.github/actions/build-docker-image
        with:
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          docker_image: ${{ env.IMAGE_NAME }}
          docker_file: 'deployed'
          docker_env: ${{ env.ENVIRONMENT }}
          base_image_tag: 'latest'
          docker_tag: ${{github.ref_name}}
          github_token: ${{ secrets.GITHUB_TOKEN }}


  ecs-deploy:
    name: Trigger deployment on ECS
    needs: docker-build-staging
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: 'staging'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to ECS
        uses: ./.github/actions/deploy-to-aws
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          aws_cluster_name: ${{ secrets.AWS_CLUSTER_NAME }}
          aws_api_service_name: ${{ secrets.AWS_API_SERVICE_NAME }}
